### ISSUE TITLE
Issue with protobuf-net

### ISSUE THREAD

**Issue by Goffen** [SteveGilham/altcover#102]
Im trying to run AltConver on my project. But I get following error

Method 'GetSerializerCore' on type 'ProtoBuf.Meta.RuntimeTypeModel' from assembly 'protobuf-net, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null' is overriding a method that is not visible from that assembly.

using .net core 3.1 and running it using `dotnet test /p:AltCover=true`

Don't really know what the problem is. Any clues?

**Comment by SteveGilham** [comment]
That sort of message would arise when a set of assemblies use `InternalsVisibleTo` in amongst themselves; in this case the original `protobuf-net.dll` has a strong-name and references a dependency assembly containing an `internal` base type.

If such a third-party assembly is instrumented, without being able to supply the original key, the friendship link is broken.

As you probably aren't too interested in the code coverage within the protobuf SDK anyway, simply excluding these dependency assemblies by use of the `/p:AltCoverAssemblyFilter` option should bypass this behaviour
Since it

**Comment by Goffen** [comment]
@SteveGilham thx alot! Bypassed now.
