### ISSUE TITLE
dotnet add package AltCover error

### ISSUE THREAD

**Issue by alex-jitbit** [SteveGilham/altcover#104]
When I run `dotnet add package AltCover`

I get this:

```
Determining projects to restore...
C:\xxxxxxx\myproject.csproj(1063,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\3.1.403\Microsoft\VisualStudio\v16.0\WebApplications\Microsoft.WebApplication.targets" was not found. Confirm that the expression in the Import declaration "C:\Program Files\dotnet\sdk\3.1.403\Microsoft\VisualStudio\v16.0\WebApplications\Microsoft.WebApplication.targets" is correct, and that the file exists on disk.
Unable to create dependency graph file for project 'C:\xxxxxxxxxx\myproject.csproj'. Cannot add package reference.
```

Tried adding the nuget manually in VS - still getting the same error when trying to run `dotnet test`

**Comment by SteveGilham** [comment]
Without a repro to work with, I'm just going to have to go by intuition here.  

The issue is presumably a clash between what AltCover in injecting by way of extra targets and some other part of the project. Where the error message says "Confirm that the expression in the Import declaration ... is correct", my expectation is that the indicated line is a part of an `<Import>` declaration, probably with a `Condition=` that's being unexpectedly set.  

Given quite how large the line number is, it looks like there is substantial customization going on in your project, and thus a large surface where the two sets of MSBuild data could interfere.  Looking at the `AltCover.targets` file, I can spot a few property names that I have neglected to add an "AltCover" sigil to, to wit

* NetCoreEngine
* NetStdEngine

in a global scope, and 

* InputDirectory
* OutputDirectory

within one of the targets.  An overloading of one or more of these would be the obvious first point of overlap.

**Comment by alex-jitbit** [comment]
Ok, I will keep investigating from there.

PS. theres no customization, it's just a plain ASP.NET web application by the way

**Comment by SteveGilham** [comment]
FWIW, I tried to repro by creating a new ASP.NET web application myself, but that ended up with a project file consisting entirely of
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

</Project>
```
so I'm not sure where the other thousand-plus lines could have come from

**Comment by alex-jitbit** [comment]
@SteveGilham our project is not "Core", it's an ASP.NET MVC app (based on the "classic" .NET Framework).

The thousand-plus lines is because it lists all the files included in the project.
