### ISSUE TITLE
JSON coverage format

### ISSUE THREAD

**Issue by ffMathy** [SteveGilham/altcover#115]
I'd love if there was a way to get the coverage reports as JSON coverage format, for performance reasons. JSON is much easier to parse than XML, and I (for instance) convert the XML to JSON first for that very reason.

However, this is obviously very heavy for such a large file.

**Comment by SteveGilham** [comment]
Do you have a spec for this "JSON coverage format"?

**Comment by ffMathy** [comment]
Not necessarily, but the same data as the default XML format would be nice.

In reality though, the only thing I need personally, is the tracked methods, sequence points, and files.

**Comment by ffMathy** [comment]
I also think JSON would be more lightweight (take up way less bytes), and less expensive in general to parse.

**Comment by SteveGilham** [comment]
The formats both have a similar amount of necessary punctuation, and JSON makes much more liberal use of whitespace in prettified form.  Attached, 5344 byes of XML directly converted gives 15438 bytes of pretty format and 4904 bytes minified -- but then the XML can have whitespace stripped as well, giving a one-line XML file of 4607 bytes.

[xmltojson.zip](https://github.com/SteveGilham/altcover/files/5841363/xmltojson.zip)

**Comment by ffMathy** [comment]
Interesting, I did not expect that actually. I stand corrected!

By the way, do we currently indent with spaces?

If we do, we could switch to `\t` characters to reduce the amount of space needed.

**Comment by ffMathy** [comment]
But the other point is the same. When I look at various benchmarks, JSON parsing always comes up on top compared to XML, in terms of performance.

**Comment by SteveGilham** [comment]
The XML reports are emitted with `XDocument.Save()` which uses a fixed 2 space indent increment.  Basically, I leave the low level XML operations all to library functions.

Having done a quick search, it looks like there are already many JSON code-coverage formats out there, none with obviously locatable specs -- including Elm, R, Istanbul, LLVM and of course coverlet -- and any of which would need to be extended to report the tracking info which you are using, of that I am sure, if not to deal with semantic units other than a source file as well.  So I might as well define my own format as well.

**Comment by ffMathy** [comment]
I see!

What about a 1-space increment then? The good thing about a tab character, is that you can configure your IDE yourself to how wide you want the tab-indentation to be. But tabs vs spaces is always a bit political, and highly opinionated, so I'll leave that to you. The savings of that 1 byte per indentation is probably not that much either way.

Yes. The JSON world is generally quite schema-less unfortunately. While there is indeed a JSON schema, it's not widely used and/or supported.

I think rolling your own would make a lot of sense. Perhaps performance of the generation can even be improved, if you didn't have to conform to some specific specification?

**Comment by ffMathy** [comment]
By the way, as for the JSON, consider using `System.Text.Json` which is now inbuilt from .NET Core 3 and onwards (also in .NET 5). It is a zero-allocation super-high-performance JSON serializer and deserializer.

`Newtonsoft.Json` is incredibly slow.

Or, even better, `Utf8Json` which is even faster.

Benchmark:
https://user-images.githubusercontent.com/46207/30883721-11e0526e-a348-11e7-86f8-efff85a9afe0.png

**Comment by SteveGilham** [comment]
In the new [v7.6.812 release](https://www.nuget.org/packages/AltCover/7.6.812), there's a * `/p:AltCoverJsonReport=`"path to JSON format result" option (and equivalents for other means of invocation). The JSON is a direct map of the XML (be it OpenCover or NCover format), with values appropriately typed -- compare [input](https://github.com/SteveGilham/altcover/blob/258fd5d2af5cd292fc6bdfb2a7f6c4ac1e9a9c7d/AltCover.Tests/Sample4FullTracking.xml) and [output](https://github.com/SteveGilham/altcover/blob/258fd5d2af5cd292fc6bdfb2a7f6c4ac1e9a9c7d/AltCover.Tests/OpenCover.json) -- though you may want to prettify the latter.

Since the original data only comes together in the XML document, and `System.Text.Json` doesn't handle `System.Xml.Linq` types, I rolled my own `XDocument` walker and used the JSON library I already link for manipulating the `.deps.json` files (`System.Text.Json` doesn't do mutability of the JSON either).  At least being in total control of the process I could inject a knowledge of the data types being represented as strings.

**Comment by ffMathy** [comment]
Hmmm, are you converting from XML to Json after the coverage has been generated, or are you directly emitting to json?

And aren't you afraid that rolling your own implementation has poorer performance than a version created by the open source community?

**Comment by SteveGilham** [comment]
Of necessity, converting from the XML to JSON as a post-process step, as the XML is the only place (barring a major rewrite) where all the information comes together in a useful form.  The process goes

1. Instrument the code, emitting the zero-coverage XML report, and a customised recorder assembly that knows what to record and for what XML format and where.
2. Run the instrumented code to generate a collection of code location visits ("point N was visited, optionally with context data")
3. Use those visits to fill in the XML (i.e. map whatever value of N into the actual sequence, branch or method point)
4. Optionally post-process the now useful data into some other format (Lcov, Cobertura, JSON,...)

In "classic" mode (as it was in [the original NCover 1.5 emulator](https://github.com/SteveGilham/dot-net-coverage) that AltCover descends from), the minimum of step 3 (just filling in the visit count records) happened in the `ProcessExit` grace period.

With `vstest`'s much tighter limitations on such an interval for the system under test, that's not an option, so what happens is that a data collector gets involved which writes a flat binary representation of the visits to a file, which gets picked up by a new third process.  Having an extra process, that doesn't have a guillotine hanging over it, allowed filling in such extras as the `<Summary />`  and method, class and module level total visits data in the OpenCover format, and also offers the luxury of adding step 4.

Having now at least got a "what the JSON should look like" stake in the ground for the existing report formats, there's one obvious performance improvement I can now make, which is cutting out the middle-man in generating the eventual string.

In the longer term, there is always that major re-write, of course.

**Comment by ffMathy** [comment]
Great explanation!

And yes, I believe a rewrite perhaps could make sense, purely from the perspective of JSON being faster to parse and also write.

Thank you for all this. It makes perfect sense.

**Comment by SteveGilham** [comment]
You may be interested in a preview of the upcoming 8.0 release with integrated JSON reporting

[altcover.8.0.205-github-pre.nupkg.zip](https://github.com/SteveGilham/altcover/files/5976042/altcover.8.0.205-github-pre.nupkg.zip)

* Native JSON report formatting (`--reportFormat=Json` or equivalents), a superset of coverlet's JSON
* Because int64 doesn't fit as a double, tracking-related timestamps are represented as Base64Encoded strings of the ticks count as a network byte order quantity `Convert.ToBase64String(BitConverter.GetBytes(IPAddresss.HostToNetworkOrder(ticks)))`
* the `xmlReport` argument or equivalent just becomes `-r, --report`
* the stop-gap `--jsonReport` collection option from v7.6 is withdrawn
