### ISSUE TITLE
AltCoverAssemblyExcludeFilter documentation appears to be wrong

### ISSUE THREAD

**Issue by sixeyes** [SteveGilham/altcover#124]
In the dotnet test integration page

https://stevegilham.github.io/altcover/%60dotnet-test%60-integration

the example

dotnet test /p:AltCover=true /p:AltCoverReport=".\altcover.xml" /p:AltCoverAssemblyExcludeFilter=NUnit

is described as removing NUnit3.Adapter but in my experience I need to use /p:AltCoverAssemblyFilter=NUnit.
There is a similar issue with this parameter a few lines earlier.

**Comment by SteveGilham** [comment]
The technical difference between the two is that ` /p:AltCoverAssemblyExcludeFilter` re-writes any excluded assembly to update any changed assembly references, including changes to strong naming keys, whereas `/p:AltCoverAssemblyFilter` just copies the excluded assembly verbatim and omits it from the more detailed inspection process.  This is of more interest for use on .Net Framework and Mono, as the new cross-platform `dotnet` is forgiving of strong name differences, 

In practice this means that, for OpenCover format output, a command line like 
` dotnet test /p:AltCover=true /p:AltCoverAssemblyExcludeFilter=NUnit /p:AltCoverReportFormat=OpenCover  dotnettest.fsproj ` 
generates coverage files like
```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<CoverageSession xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Summary... />
  <Modules>
    <Module hash="C5-B5-24-4C-81-A2-66-9B-C6-42-31-69-5A-EE-C0-4E-08-DC-0F-0C">
      <Summary ... />
      <ModulePath>...\bin\Debug\netcoreapp2.1\dotnettest.dll</ModulePath>
      <ModuleTime>2021-04-17T17:20:35.25064Z</ModuleTime>
      <ModuleName>dotnettest</ModuleName>
...
    </Module>
    <Module skippedDueTo="Filter" hash="B7-1D-40-9A-EB-95-E7-D6-7D-5A-B2-06-61-B7-2E-66-2E-63-08-09">
      <ModulePath>...\bin\Debug\netcoreapp2.1\NUnit3.TestAdapter.dll</ModulePath>
      <ModuleTime>2020-07-11T16:23:34Z</ModuleTime>
      <ModuleName>NUnit3.TestAdapter</ModuleName>
      <Classes />
    </Module>
  </Modules>
</CoverageSession>
```
marking the NUnit assembly as considered, but excluded, whereas
`test /p:AltCover=true /p:AltCoverAssemblyFilter=NUnit /p:AltCoverReportFormat=OpenCover dotnettest.fsproj ` 
generates
```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<CoverageSession xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Summary ... />
  <Modules>
    <Module hash="11-42-D3-E3-49-BF-AE-38-C9-34-B7-8C-69-50-BD-BE-07-E1-AF-A6">
      <Summary ... />
      <ModulePath>...\bin\Debug\netcoreapp2.1\__Saved_dotnettest\dotnettest.dll</ModulePath>
      <ModuleTime>2021-04-17T17:20:48.7434216Z</ModuleTime>
      <ModuleName>dotnettest</ModuleName>
...
    </Module>
  </Modules>
</CoverageSession>
```
which completely omits the filtered assembly.  This, one could argue is technically incorrect OpenCover output, and that it should be the same as the previous case -- but then AltCover similarly omits assemblies that were passed over for lack of symbols, whereas OpenCover includes them with a `skippedDueTo` attribute, and no classes.

For completeness' sake -- Json format output for the `AltCoverAssemblyExcludeFilter` has an empty record for the NUnit assembly, rather than no trace at all for `AltCoverAssemblyFilter`; for NCover format the difference is a
```
  <module moduleId="5a27f604-7c2d-4037-b872-9e9d97b9518c" name=...\bin\Debug\netcoreapp2.1\NUnit3.TestAdapter.dll" assembly="NUnit3.TestAdapter" assemblyIdentity="NUnit3.TestAdapter, Version=3.17.0.0, Culture=neutral, PublicKeyToken=null" excluded="true" />
```
record being present in the former case and not in the latter.

**Comment by sixeyes** [comment]
Thanks for the explanation. Not sure why I couldn't get the Exclude filter to work, but it's working now.
