### ISSUE TITLE
`inline` is not ignore as it may should be.

### ISSUE THREAD

**Issue by aloisdg** [SteveGilham/altcover#128]
Hello,

I may forgot something but I dont know why inline function is seen as not covered. Well, it is technically true because the function is inlined by the compiler. But this should not be seen as red, shouldn't it?

with inline

![image](https://user-images.githubusercontent.com/3449303/116813177-cb375080-ab52-11eb-9bea-67be47d5b649.png)

without inline

![image](https://user-images.githubusercontent.com/3449303/116813198-ed30d300-ab52-11eb-8cd6-2c9da9252b3a.png)

Cheers,

**Comment by SteveGilham** [comment]
This is an annoying, but expected pheonomenon.  When the F# compiler inlines a method, it compiles the code almost as if the inlined method had been copied into place in the call site at the source level.  The "almost" is because even a multi-statement function being inlined (e.g. the built-in `string` function) will become part of the single statement including the call site.

In particular, there is no debug information pointing at the original location of the method; just the one very large statement each time it is invoked.

The workround, if you want that line to go green, is to do something like
```
    let
#if !DEBUG
         inline
#endif
                  internal selectNodes (node:XmlNode) name =
```
assuming coverage testing on the debug build.

**Comment by aloisdg** [comment]
This is a functional workaround I may use but I don't really like that an external tool alter like this the way I write a function. I will think about it. Thank you for the answer. I will close this issue for now. Have a nice weekend if it is the weekend wherever you are. :)

**Comment by SteveGilham** [comment]
The real fix would require an F# compiler enhancement that would bring in the debug sequence point information from the source assembly where available (or, possibly, where available from the same assembly), which would also enable what is not currently possible -- stepping through an inlined function in the debugger.

**Comment by SteveGilham** [comment]
Related -- https://github.com/dotnet/fsharp/issues/9176
