### ISSUE TITLE
Support for Source Generator

### ISSUE THREAD

**Issue by latop2604** [SteveGilham/altcover#131]
Hello, 

I use altcover (global tool) to generate code coverage for an .Net5.0 app. And use the result as open cover format to generate report with [Report-Generator](https://github.com/danielpalme/ReportGenerator).

The line coverage is ok. But report generator is unable to find related file. (Understandable as source generated file are in memory only by default.

I don't know if it's in altcover scope or in report generator. Or both. 

And btw, thx for your great work on this tool.

![image](https://user-images.githubusercontent.com/2058133/138093623-ad4577ba-a0d7-42fe-85da-2104d66f3f6f.png)

**Comment by SteveGilham** [comment]
Any .net coverage tool relies on the debug information that is present in the .pdb file to tie the compiled IL to the original source.  In the case of source generators -- having just now built and played with [the official sample solution](https://github.com/dotnet/roslyn-sdk/tree/main/samples/CSharp/SourceGenerators/SourceGeneratorSamples) -- it seems that the compilation process invents file names under a notional folder `$(ProjectDir)\[Generator Assembly Name]\`, and presents them in the debug information as if they were real.

There's no easy labelling on the code that results -- no `[GeneratedCode]` or similar attributes, so there's no quick fix work-around I can offer.  It looks like I need to extend the `--localSource` flag to skip parts of an assembly, on a method by method or even line by line basis, rather than just testing the first line of code it sees, now that it turns out that the possibility exists of such phantom files.

There are also some interesting bits in the debug metadata that will bear further investigation -- embedded source blocks, which may actually represent the generated code, for example.  Such things would make sense combined with the rest of the debug information as enabling step-into debugging, after all, and might be of use for reporting purposes.

**Comment by SteveGilham** [comment]
You forgot to obfuscate your file names here :relaxed:

That would help ReportGenerator turn the current coverage information into a proper listing with red/green coverage indication -- that program would need to know per assembly the relative path from `$(ProjectDir)` to `obj\...\generated`; the choice of target platform, and the possibility of customization in the project of `$(IntermediateOutputPath)` means it can't be automated.  If the .pdb file does indeed contain the generated code embedded source, then it could be given the location of the (possibly embedded) .pdb files instead.

The same issues would also apply to the AltCover Visualizer, of course.  That would be the opposite tack to simply suppressing the non-existent auto-generated code from coverage.

I think this might keep me busy through the .net 6 release and resultant tooling upgrades I'd been planning to absorb.

**Comment by SteveGilham** [comment]
This is now feature complete and will be in the next release of AltCover.

**Comment by SteveGilham** [comment]
Released as [v8.2.828](https://www.nuget.org/packages/altcover/8.2.828).
