### ISSUE TITLE
Branch Coverage not reporting the same branch coverage on the same line in two different classes in the same assembly.

### ISSUE THREAD

**Issue by simkin2004** [SteveGilham/altcover#143]
Originally thought my issue was #90, but realized that none of the methods are async methods.

I am getting 2 of 4 branches covered when calling "using(var connection = this.ProviderFactory.CreateConnection())" in one class and full branch coverage when calling the same method the same way in another class in the same assembly.

In both classes, the DbProviderFactory is passed in on the constructor of the class and is guaranteed to be not-null by a check in the constructor.

There are two unit tests for each class that ensure that the branch coverage on both the null and non-null branches of DbProviderFactory.CreateConnection() are covered.

In the same unit test run with the same configuration on a single assembly, one class shows that the specified code line is Branch Fully Covered and the other class shows 2 of 4 branches covered.

I have not been able to reproduce this issue in a smaller test set.

I have a attached the csproj, offending .cs files, and offending MsTests, and a screenshot of the SonarCloud showing the discrepancy.
[Branch-Coverage-Failure.zip](https://github.com/SteveGilham/altcover/files/8201664/Branch-Coverage-Failure.zip)

If you need the links to the code, tests, or SonarCloud, I can provide them.

**Comment by SteveGilham** [comment]
On more detailed inspection, the difference turns out to be that the code generated for the state machine code in `SupplementContextWithDatabaseRecordStep/<InvokeCoreAsync>d__4::MoveNext()` has only one generated `switch` based on the state, and that in a context such that the generated nature of the branching is "obvious" and so is ignored in the coverage, whereas `SaveContextToDatabaseStep/<InvokeCoreAsync>d__4::MoveNext() has two separate such `switch`es,, and the interaction between them means that the second one is not being detected as generated.

So, it's really  a false positive here; and a deficiency in the heuristic to detect such.

**Comment by SteveGilham** [comment]
Should be resolved in [release 8.2.836](https://www.nuget.org/packages/altcover/8.2.836)

**Comment by simkin2004** [comment]
Thank you!  Thank you!  Thank you!  Thank you!  Thank you!  Thank you!  Thank you!  Thank you!  A million times THANK YOU!
