### ISSUE TITLE
Code coverage turns out to be 0 for instrumented DLLs of the server from agent machine

### ISSUE THREAD

**Issue by tilak-nanavati-opshub** [SteveGilham/altcover#149]
Hi Steve,

We are trying to get the coverage of the DLLs which are residing in the **central server**. We are using an **agent machine** that runs all the commands, right from shutting it down. instrumentation, coverage collection on **central server**.  

When we try to instrument the binaries of the central server from the **agent machine**, we can see the coverage.xml and coverage.acv files being created. Then after restarting the service we are performing several actions (which use the service to get line hits).  At the end, we gracefully shut down the service and try the collect the coverage and get it in the Cobertura format. We have observed that the collected coverage comes as 0 only.

Detailed steps performed:
===============================

> 1. Shut down IIS service. [tried with batch file and manual shut down]
> 2. Run the following code (from the **agent machine**):
> altcover --save --inplace -i "\\sharing_path_to_service\Service\bin" --assemblyFilter "^(StackExchange.Redis)"
> 3. Start IIS service.
> 4. Run manually some tests.
> 5. Gracefully shut down IIS service.
> 6. Run the following command (from the **agent machine**):
> altcover runner --collect -r "\\sharing_path_to_service\Service\bin"
> 7. altcover runner --collect -r "\\sharing_path_to_service\Service\bin" -c="agent_machine_path\coverage.xml"

Note: Here, the **sharing_path_to_service** denotes the path of central server service folder (it is other VM), and **agent_machine_path** denotes the path of **agent machine**, where we are standing.

Observation 1:
==========
When we performed all the operations from the central server machine, we could see that the coverage was getting populated. In that case, there was no intervention from **agent machine**. Everything is done in the same central server.

Observation 2:
==========
When we performed all the operations from the **agent machine** from "C:/Altcover_Folder", we received an error after starting the service from central server that the directory "C:/Altcover_Folder" does not exist. While setting the altcover watchers it failed. Because ideally there is no such directory present on the central server (where all the instrumented DLLs are present).

Issue being faced:
============
Is there any way we can capture the coverage for a service that is running on a different machine (other than the one on which we are executing the commands to the instrument and collect the coverage)?

> Or is there any parameter that we can add to the above command, that explicitly mentions the path where coverage.xml and coverage.acv files need to be generated?

It would be a great help if by some means we can achieve this.

Thanks!

**Comment by SteveGilham** [comment]
I confess that I had never considered the possibility of a distributed run-time environment being used for coverage testing before now.

All the coverage-related run-time configuration, including the report file location. gets baked into the `AltCover.Recorder.g.dll` assembly (as an absolute file path, composed with respect to the working directory at instrumentation time as needed) at the point of instrumenting the code.  This is what allows the separate processes  `altcover save`/run program/`altcover collect` approach to agree on where the coverage data is.  The `collect` phase uses the recorder directory (the `-r` parameter) to find the `AltCover.Recorder.g.dll` assembly with the coverage file path in, and because that path is absolute, doesn't need to worry about what the working directory is during the `collect` phase when looking for the accumulated coverage data.

Generalising this for a distributed system, the simplest approach -- and one that should work with the code as it stands -- would be to give an explicit fileshare location for the coverage file, like

`altcover --save --inplace -i "\sharing_path_to_service\Service\bin" --assemblyFilter "^(StackExchange.Redis)" -r "\\mydatacollector\reports\coverage.xml"`

with the usual caveats that the file share should refer to one and the same place for all the involved service hosts, and the directory be writeable by the service processes.

An alternative "some assembly required" approach, but one that would also cut down on the fileshare-related network traffic during the run, would be to give an explicit absolute location referring to a writeable directory that would exist on each involved machine separately e.g.

`altcover --save --inplace -i "\sharing_path_to_service\Service\bin" --assemblyFilter "^(StackExchange.Redis)" -r "C:\temp\coverage-<uniqueID>.xml"`

where `<uniqueID>` is some run identifier (time-stamp, GUID, whatever), then after the run collecting all the related `.acv<number>` files,  renumbering to avoid clashes, on the machine where you are going to run `altcover collect` (along with the blank coverage report file generated on the host used for the instrumentation run, if different).

**Comment by tilak-nanavati-opshub** [comment]
Thank you so much Steve for the detailed explanation. 

We will certainly perform these steps and share the update.

Thanks !!!

**Comment by tilak-nanavati-opshub** [comment]
Hi Steve,

We tried the approach -- explicitly providing the coverage file location along with the instrumentation command.
`altcover --save --inplace -i "\sharing_path_to_service\Service\bin" --assemblyFilter "^(StackExchange.Redis)" -r "\\mydatacollector\reports\coverage.xml"`

It worked like a charm. 

Thank you once again for providing a detailed explanation along with this solution.

**Comment by SteveGilham** [comment]
Glad to be of service.
