### ISSUE TITLE
Provide a use case for a web application and describe better the role of the "runner" 

### ISSUE THREAD

**Issue by lucaregini** [SteveGilham/altcover#16]
I have instrumented a web application (with the --opencover flag) however while the cover.xml file has been correctly created the results obtained weren't meaningful at all.
I have used an application compiled in release mode with symbols enabled ( so I had the pdb for the release assemblies). I have not used the runner mode.  Is there any catch that must be known about collecting coverage for web applications? 
Also the role and purpose of the runner is not clear. Reading trough the documentation I had the impression that it's only used to translate the raw coverage data collected at a previous step into a more elaborated one ( such as open cover xml).

**Comment by SteveGilham** [comment]
Use case [here](https://github.com/SteveGilham/altcover/wiki/Use-Cases#use-case--web-application)
Runner mode discussion [here](https://github.com/SteveGilham/altcover/wiki/Usage#runner-mode--what-gives)
The main catch is that the web application does need to be shut down gracefully so that the coverage data get flushed to disk.
