### ISSUE TITLE
Some tests take an abnormally large amount of time when running under AltCover

### ISSUE THREAD

**Issue by ioana-lodro** [SteveGilham/altcover#164]
Hi Steve!
I am opening this bug because my team and I are not sure how to proceed.

**Some background:**
A while ago we had some trouble when using vstest in combination with AltCover, for which I opened this (now closed) issue: https://github.com/SteveGilham/altcover/issues/159
Long story short, we were initially using a single command to run vstest under AltCover, but could not always get the coverage data. Then we switched to 2 commands, as per your advice, so we no longer have that problem.

As would be expected, the tests take a bit longer to run under AltCover than they would otherwise (for example, a test would take 300ms without AltCover and 500ms with AltCover).

**The issue**
However, for some of our projects, the test time has gone up by a very large amount of time. Most tests on these projects still only have a small increase in time, like the example above. But a few of them have increased from 12 seconds to around 3 minutes - so 10 of these tests would add an extra half an hour to the total test time of a project (it used to be around 1-2 minutes and it's now 
over 30 minutes).
Additionally, they way we ran AltCover before (in a single command that instrumented the code and gathered the coverage output), we did not have this issue. Test times did increase by a bit, but total testing time was still only 2-3 minutes.

Do you have any idea what could cause this and how we might fix it?

Thank you and have a nice weekend!

**Comment by SteveGilham** [comment]
There's an unfortunate trade-off between ensuring that coverage gets reliably recorded, and the overhead of recording each visit.  Reliability moves to writing visit data to file during the test, rather than waiting until the end and hoping to finish everything during a process exit handler -- which, as the previous issue showed, was not always sufficient.

Depending on your needs, you can reduce the amount of recording being done by choosing `--single` to only write the first visit to a location, and perhaps `--linecover` to omit the branch coverage information.

Alternatively, as your examples were using `vstest.console.exe`, you can work around its aggressive process termination by using the in-process data collector `AltCover.DataCollector.dll` through a runsettings (`/Settings:local.runsettings`) file looking like 
```xml
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
  <InProcDataCollectionRunSettings>
    <InProcDataCollectors>
      <InProcDataCollector friendlyName="AltCover" uri="InProcDataCollector://AltCover/Recorder/[version]" assemblyQualifiedName="AltCover.DataCollector, [AltCover.DataCollector assembly full name]" codebase="[path to AltCover.DataCollector.dll]">
        <Configuration>
          <Offload>true</Offload>
        </Configuration>
      </InProcDataCollector>
    </InProcDataCollectors>
  </InProcDataCollectionRunSettings>
</RunSettings>
```
with the bracketed values filled in according to the altcover installation.  Depending on your build process, it may be simpler to emulate what the `dotnet test` integration does, and execute the [`AltCover.RunSettings` MSBuild task](https://stevegilham.github.io/altcover/AltCover.Engine/Tasks-fsapidoc#task-altcoverrunsettings) from the `AltCover.Engine` assembly to fill in the blanks, like -
```xml
    <AltCover.RunSettings
      TestSetting="$(VSTestSetting)"
      Verbosity="$(AltCoverVerbosity)">
      <Output TaskParameter="Extended" PropertyName="VSTestSetting" />
    </AltCover.RunSettings>
```
where `VSTestSetting` is any existing runsettings file (or empty) on input, and is here updated to point to an extended version in a new temporary file with the AltCover information added.

The use of the data collector should implicitly set the `--defer` option to hold all the recording data in memory and write only at the end of the test process, but it would cause no harm to explicitly specify it along with the runsettings file.

**Comment by ioana-lodro** [comment]
Hi Steve!

Many thanks for answering so quickly!
Regarding the usage of MSBuild tasks in AltCover, this is something that our build process can't handle. We build everything using an SDK that we wrote (in MSBuild), and I remember the first thing I wanted was to use when we implemented code coverage with AltCover was the MSBuild tasks. Unfortunately, the way we designed the build steps, it's not possible.

We run a test step independent of restore, build and other MSBuild targets that run, and this is also the reason we don't use dotnet test (because it builds first and executes tests afterwards).

The good news is I can try and make a version of our SDK that uses a runsettings file - hopefully this will work. It will take some time to implement, but if you wouldn't mind, I'd like to keep the issue open until then.

Thanks again! I'll let you know how it goes.

Have a nice day!

**Comment by ioana-lodro** [comment]
Hi again!

After several tries with a runsettings file (with a couple different ways of calling AltCover), we finally decided to leave it as-is. The dev teams that use it have the option of disabling it from their builds if it takes more time than they're willing to let it take.

As such, I'm closing this issue.

Thank you for your help and for making AltCover available to so many projects! :)

Have a nice weekend!
