### ISSUE TITLE
Looking to add expecto support

### ISSUE THREAD

**Issue by voronoipotato** [SteveGilham/altcover#2]
Hey Steve, if I were looking to add expecto support to altcover what do you expect the workload would be?

https://github.com/haf/expecto/issues/219

In here I talk about what sort of steps could give us partial support in OpenCover, by leveraging attribute based test tracking, however it would also be nice to track certain methods by name such as ```runTestsInAssembly```
```runTestsWithArgs```
```runTests```. Hopefully I can be of use?

**Comment by SteveGilham** [comment]
While test tracking is something on my roadmap in next phase, it's not something I've done a detailed breakdown of yet.  Off the top of my head we would need

1. Adding an indication of what data to gather to the recorder assembly during the instrumentation step alongside the report file location -- this is likely to be the most interesting part of the process, since we can inject arbitrary IL if it's required.
2. The Visit function would need to look up the call stack based on that information and add what it finds to the in-memory or file-based record
3. Then the write-to-file step will just add the extra data into the in-memory document

**Comment by SteveGilham** [comment]
The overall test tracking feature, of which this is a special case, is currently in progress.  That still means that it'll be ready when it's ready and not before.

**Comment by SteveGilham** [comment]
If you want to live on the bleeding edge, then I have an absolute "meets minimum" that could be taken and tested as of commit [1704e95](https://github.com/SteveGilham/altcover/commit/1704e95d73340d6457bd7eae0a5e0e31ab84770d).  You'll need command line parameters `--opencover -c=runTestsInAssembly -c=runTestsWithArgs -c=runTests` to pick up methods with those names, plus arguments for any attributes you also want to tag; and then use the "runner" mode to invoke the extended coverage gathering.  Current limitation is that you have to instrument the test code for coverage in order to also get the extended call tracking instrumentation -- but that will be after I've finished adding test automation for the current state of play.

**Comment by SteveGilham** [comment]
The latest release, 2.0.350 has the customisable `--callContext` argument to let you specify whatever method or attribute names you wish by way of visit collection.

Have fun!

**Comment by SteveGilham** [comment]
Closing, in the absence of further activity.

**Comment by haf** [comment]
Was this implemented? It would be awesome to have this support. (I just discovered your project)

**Comment by haf** [comment]
Seems like @theangrybyrd got it working https://github.com/haf/expecto/issues/219#issuecomment-374810994

**Comment by TheAngryByrd** [comment]
@haf I'm gonna take a look at integrating https://github.com/SteveGilham/altcover/issues/7 into  https://github.com/TheAngryByrd/MiniScaffold today

**Comment by voronoipotato** [comment]
wow nice! This is really awesome

**Comment by TheAngryByrd** [comment]
Forgot to mention, I added https://github.com/TheAngryByrd/MiniScaffold/pull/85 a while back.  Seems to work well.

**Comment by SteveGilham** [comment]
You're welcome. 

You are about [a dozen releases out of date ATM](https://github.com/TheAngryByrd/MiniScaffold/blob/a8b6cd7f49c934731b06f679c6d7ec62f9a2335e/Content/paket.lock#L1348), though, and, in particular, 3.0.490 contains a ton of bloat from redundant PowerShell core runtimes that are removed in 3.5.xxx -- not to mention the various core functionality bug-fixes in more recent releases.

**Comment by TheAngryByrd** [comment]
From the getting started guide, it looks like i don't need https://github.com/TheAngryByrd/MiniScaffold/blob/master/Content/tests/Directory.Build.targets any longer.  Does that seem right?

**Comment by SteveGilham** [comment]
That's correct -- not since build 3.0.488, or really, given the screw-up with that release (related to the powershell bloat), since 3.0.490 --  i.e. the one you've been using all along, as it happens
