### ISSUE TITLE
[enhancement] integration with xharness and/or device runners for iOS and Android

### ISSUE THREAD

**Issue by amirvenus** [SteveGilham/altcover#203]
As .net also runs on mobile platforms, it would be great if we could collect the code coverage using a combination of altcover and xharness

**Comment by SteveGilham** [comment]
[Release 8.8.10](https://www.nuget.org/packages/altcover/8.8.10#releasenotes-body-tab) offers the `--portable` option, which puts the coverage report, control file, and intermediate data files in the same directory as the recorder assembly, so allowing the whole instrumented application including the report file to be moved between filing systems.

Rather than tangle with specific technologies, this should be a general purpose solution that would allow a process of instrument, deploy to test environment, do tests, copy back, and then collect the coverage data into the report.

**Comment by SteveGilham** [comment]
Believed addressed, closing.
