### ISSUE TITLE
Question Regarding assemblies being added to code coverage result

### ISSUE THREAD

**Issue by bigboybamo** [SteveGilham/altcover#217]
Hi,

I am new to atlcover, 
I ran To generate my xml file
````
dotnet test /p:AltCover=true
````
 and then used  [Report generrator](https://reportgenerator.io/) to visualize it. 

But then,  I'm wondering my why these assemblies where added since I just imported the libraries and didnt actually write any code there
<img width="844" alt="image" src="https://github.com/SteveGilham/altcover/assets/60369677/f4670484-4fc1-49ac-b08a-6884486c2181">

<img width="839" alt="image" src="https://github.com/SteveGilham/altcover/assets/60369677/c32fa4e9-ac35-449c-ab27-d0f156b42976">

Maybe I am missing something?

edit: Or is it possible to define only the projects i want coverage on in dotnet test /p:AltCover=true ?

For more context, this what i  get when i ran the command in the cmd
<img width="854" alt="image" src="https://github.com/SteveGilham/altcover/assets/60369677/f48485bb-fe03-4d9c-ad17-56c15d179ec1">

**Comment by SteveGilham** [comment]
The short answer is that I do not know which assemblies are the ones you are interested in. I can't  (for example) just automatically exclude `Microsoft.*` assemblies, because a Microsoft engineer might well be using this tool. I certainly can't automatically exclude `AltCover.*` assemblies since I use to tool in self-testing.

The long answer is that it used to be the case that third party libraries arrived without `.pdb` files for the symbols needed to determine where lines of code mapped to the compiled assembly, so would automatically be excluded from coverage tracking, but the arrival of ubiquitous embedded symbols over the past decade or so has invalidated this assumption.

Often `dotnet test /p:AltCover=true /p:AltCoverLocalSource=true` or `dotnet test /p:AltCover=true /p:AltCoverAssemblyFilter="?[my product name]"` will do what you require, but even those may require more fine tuning.

**Comment by bigboybamo** [comment]
Hi @SteveGilham  

Running `dotnet test /p:AltCover=true /p:AltCoverLocalSource=true` fixed my issue.

many thanks
