### ISSUE TITLE
Code line execution count is incorrect with 9.0.1 but worked with 8.9.3

### ISSUE THREAD

**Issue by hfickes** [SteveGilham/altcover#233]
We noticed that our set of tests with Altcover no longer report the correct line execution count.  This worked in AltCover 8.9.3 but no longer does with AltCover 9.0.1.  I've tested this with identical code and arguments excepting which version of AltCover is used.

The fact that a line was executed during a test hasn't changed, but the information regarding how often it was executed did.  Most lines now show far fewer executions than they actually had.  A line that shows as being executed 6033 times with Altcover 8.9.3 shows as being executed 2 times when the same code/test run is done with Altcover 9.0.1.  This happens with most, maybe all, of our code.

We are using .Net Framework 4.8.  I wish we could move to latest .Net.  We use OpenCover format for the output.  I noticed the problem when using ReportGenerator to create an html report.

The command lines we use via gradle are:

-s=Scrpt.Tests -s=nunit.framework -s=NUnit3.TestAdapter -s=Common.Logging -s=Common.Logging.Core -s=AltCover.Monitor --sn=c:\\projects\\scrpt\\scrptKey.snk -- nunitConsole scrpt.tests.dll --stoponerror

followed by the "wrap-up" of:

runner --collect -r=__Instrumented

Btw, thank you for writing this tool.  It has been an immense assistance to our team.

-Herb

**Comment by SteveGilham** [comment]
This is expected behaviour, as part of the changes to make the default mode of operation produce coverage results without undue time spent processing,

As stated in [the 9.0.0 release notes](https://github.com/SteveGilham/altcover/blob/79af67ee9b8f6ba42dbaa08558c7fa3ab28a6024/ReleaseNotes.md?plain=1#L12)

> • [BREAKING] API change : `--all` and `--eager` replace `--single` and `--defer`, so the default behaviour is now deferred (Unload/Exit time) reporting, and first visit only per context.

If the totals, rather than a binary yes/no "was this code visited" are of interest, then add `--all` to your command line. 

Note that the combination of both `--all` and `--eager` is the least performant mode in the `--collect` stage.

**Comment by hfickes** [comment]
Thank you.  Guess I should read the release notes first <grin>.

Also, the 9.0 changes are better default behavior for us.  We don't usually need the line execution information but when we do, we can run the tests with the --all switch to gather that information as well.

Again, thank you for writing this tool!

**Comment by SteveGilham** [comment]
You are welcome, and thank you!
