### ISSUE TITLE
AltCoverThreshold inconsistency

### ISSUE THREAD

**Issue by TheAngryByrd** [SteveGilham/altcover#33]
I'm trying to use the `AltCoverThreshold` parameter to help with making sure my code has enough coverage however, it seems to be inconsistent with what ReportGenerator says.

I've set it to 10 percent but it claims to be not be that high.
```
 error : Coverage percentage achieved is 1% below the threshold of 10%. [/private/var/folders/14/mp4bnvkn3fq5mqcgqscm5c040000gn/T/foowhat/tests/foowhat.Tests/foowhat.Tests.fsproj]
```

However ReportGenerator says it's 100% covered.

![screen shot 2018-08-24 at 5 13 21 pm](https://user-images.githubusercontent.com/1490044/44608256-2a007580-a7c1-11e8-8825-ea3e5c048897.png)

[foowhat.zip](https://github.com/SteveGilham/altcover/files/2319913/foowhat.zip)

`build.fsx` line 104 is where I'm setting it.

**Comment by SteveGilham** [comment]
Switching on visible reporting by extending the test step arguments with `-v m`, I see the headline coverage as
```
Test Run Successful.
Test execution time: 1.8358 Seconds
  ... C:\Users\steve\source\repos\foowhat\tests\foowhat.Tests\coverage.netcoreapp2.1.xml.0.acv (168b)
  37 visits recorded in 00:00:00.0408456 (906 visits/sec)
  A total of 37 visits recorded
  Coverage statistics flushing took 0.10 seconds
  Visited Classes 4 of 81 (4.94)
  Visited Methods 5 of 82 (6.1)
  Visited Points 8 of 86 (9.3)
  Visited Branches 6 of 106 (5.66)
```
which is indeed 1% below the 10% threshold.

Looking in the xml coverage file, the 8 out of 86 is made up from 2 out of 2 in `foowhat.Say` and 6 out of 84 sequence points in the unit tests -- each `Expect.equal` call inlines a large blob of code containing hundreds of IL instructions, including many branches and dozens of nested function calls, none of which are executed in the success case.

Because _some_ of the code in lines 12 and 15 of Tests.fs is executed, ReportGenerator will show that as 100% covered, whereas a more unflattering view will reveal the partial nature of the coverage

![2018-08-25](https://user-images.githubusercontent.com/7460854/44616264-86f13f80-a844-11e8-8c97-4f78ea0542ba.png)

You may wish to exclude the test assembly from instrumentation by adding `/p:AltCoverAssemblyExcludeFilter=foowhat.Tests` to the test options.

**Comment by SteveGilham** [comment]
The filters are all regexes that work if there is any match so `/p:AltCoverAssemblyExcludeFilter="\.Tests"` has the effect you are looking for (anything containing `.Tests` as a substring.

**Comment by TheAngryByrd** [comment]
Perfect! thanks again!
