### ISSUE TITLE
.Net Core 2.1 UnitTest Got 0% Coverage

### ISSUE THREAD

**Issue by XbbLeon** [SteveGilham/altcover#34]
Hi,there is a question when I use Altcover:
Previously,I can use altcover and reportgenerator to get the coverage of my project when the classlib project is .net standard 2.0 and the unittest project is .netcore 2.0.
But recently,I update the unittest project to .netcore 2.1,I got the coverage is 0%,and I found it can't modify the coverage.xml when I "dotnet test ".
How can I get the coverage at .netcore 2.1 unittest project? Thank you.
Best wish!

**Comment by SteveGilham** [comment]
I tried to repro this by switching some of the the AltCover unit tests (specifically the ones for the recorder assembly, which itself is built against netstandard2.0) to be netcoreapp2.1, but the coverage was reported exactly as expected.  Do you have a simple repro you can share?

**Comment by XbbLeon** [comment]
Sorry，our code is not open source,so I can't share it.
I will tell you how I use the Altcover,can you give me some advices to help me get the code coverage.
1.I build classlib project to "libs" directory
2.I use Altcover.dll handle “libs” to "altdlls" directory,I use the commond:"dotnet Altcover.dll -i libs -o altdlls"
3.I build unittest project to "testdlls" 
4.I copy "altdlls" to "testdlls"
5.I dotnet test unittest project with the "testdlls" directory
After update to 2.1,I found when I do 5,the coverage.xml won't be modified in linux.But it can work in windows,are there some mistakes when I use the altercover.

By the way , if I use the Quick Start ,I can get the coverage of netcore 2.1,but it will contain the unittest code ,are there some ways I can use to ignore the unittest project code?
Thank you vary much.

**Comment by SteveGilham** [comment]
To answer the supplementary question

`/p:AltCoverAssemblyExcludeFilter=[regex to match the test assembly but not the assembly under test]`

**Comment by SteveGilham** [comment]
Looking in detail at the process you're using (steps 1 to 5 above), the first question that comes to mind is whether in step 5 you use `dotnet test --no-build` or not; without the `--no-build`, the instrumented code could well be overwritten by the build process fetching the assembly under test through the project dependency, hence no coverage.

In any case, I would strongly recommend using the direct `dotnet test` integration rather than all those manual steps; the equivalent would be to just run `dotnet test --verbosity minimal /p:AltCover="true"` in the test project folder (or `dotnet test --verbosity minimal /p:AltCover="true" /p:AltCoverAssemblyExcludeFilter=...` to hide the unit tests).

The command-line equivalent of /p:AltCoverAssemblyExcludeFilter is `-e` or `--assemblyExcludeFilter`.

**Comment by SteveGilham** [comment]
Having worked through this manually, yes, without the `--no-build`, the instrumented dll is overwritten.
