### ISSUE TITLE
Ternary operators, code optimization, and branch coverage

### ISSUE THREAD

**Issue by leighshepperson** [SteveGilham/altcover#37]
In Release mode,  (or with optimizations enabled), the function ` Gendarme.``detect ternary pattern`` ` does not detect ternary patterns in methods because the sequence of instructions differs from the non-optimized version. 

Additionally, the injected code only appears once for a method with a single ternary statement, so it does not capture the possible branches, and hence the branch coverage is incorrectly reported as 0 in these cases.

This also softly implies that altcover will differ between release and debug in other cases.

I'm wondering if altcover is only intended to run in debug mode? And if not, how difficult would it be to provide a patch? (Perhaps it's not feasible.)

**Comment by SteveGilham** [comment]
If altcover has an underlying assumption here, it's going to be that the IL it's processing looks more like what the F# compiler emits than a Roslyn compiler's output, rather than being  a preference for debug over release.

The `Gendarme` module is used to compute method cyclometric complexity -- it's a re-implementation of the part of the Mono Gendarme library that OpenCover uses for the same purpose that exists only because there isn't a .net core version of the original available.  That code may well have a tacit assumption that it would only be used on debug builds.

The code injection for branch coverage detection is intended to be agnostic as to how the IL was composed, while not triggering false positives for the many common cases where the compiler injects its own branches that only transfer control within a sequence point.

**Comment by SteveGilham** [comment]
The code of interest is of the form `return selection ? : yes : no;` which compiles to IL which returns directly from that sequence point, wherever it is found in a method.  It seems to be a fairly recognisable pattern
```
 brtrue.s label
...
ret
label: ...
...
ret
```
so that should be fairly simple to add a special case for.

**Comment by leighshepperson** [comment]
Yes, great - that addition will be extremely helpful.

**Comment by SteveGilham** [comment]
[Pre-release build 646 ](https://ci.appveyor.com/project/SteveGilham/altcover/builds/19309167/artifacts) contains the substantive change for the branch coverage, though not for all the related measures e.g. complexity.

**Comment by SteveGilham** [comment]
Should be fixed in release [4.0.649](https://www.nuget.org/packages/AltCover/4.0.649).

**Comment by leighshepperson** [comment]
Great - thank you for providing a fix, it'll be a great help
