### ISSUE TITLE
Need an example on how to run AltCover

### ISSUE THREAD

**Issue by alexey-aurea** [SteveGilham/altcover#65]
Please add another example of how to run AltCover in the "Instrument and test now, classic mode" on full .net framework to get overage for a whole solution rather than individual libraries.

**Comment by SteveGilham** [comment]
Coverage tools (of which AltCover is but one) work on the level of a single executable being run.  In its classic mode, AltCover is a near drop-in replacement for NCover (as was) or OpenCover, where the unit test run is done within the coverage tool.

Taking a position of being build-process agnostic, it's difficult to say more that that you add coverage support to the unit test runs by wrapping the calls to the test executor of choice inside the AltCover invocation.  If you want it all done to get you one big XML report (rather than using e.g. [ReportGenerator](https://github.com/danielpalme/ReportGenerator) to aggregate, then the process is 

For each unit test library project
  Copy the contents of the project $(OutputDirectory) to a shared test location
Then run AltCover in the "Instrument and test now, classic mode" over a test executor run that drives all the unit test libraries

which is a more invasive change to the build process, and assumes compatibility of all the assemblies involved.

**Comment by alexey-aurea** [comment]
Thanks, I got that out of the documentation.. The issue I am facing however is that OpenCover for example can be executed like this
.\openCover2\OpenCover.Console.exe -target:"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" -targetargs:"C:\\work\\testProj1\\bin\\Debug\\testProj1.dll C:\\work\\testProj2\\bin\\Debug\\testProj2.dll C:\\work\\testProj3\\bin\\Debug\\testProj3.dll C:\\work\\testProj4\\bin\\Debug\\testProj4.dll" -output:TestResults\OPENCOVER_VSTEST_FILE.xml which would generate one output xml over all those assemblies.
From what I understood in case of AltCover I have to do something like this
C:\temp\altCover\tools\net45\AltCover.exe /i=C:\work\testProj1\bin\Debug\ /o="C:\temp\__UnitTestWithAltCover" -s=Microsoft.* -s=nunit -s=nlog -s=System.*    /x="ALTCOVER_VSTEST_PROJ1.xml" --opencover
C:\temp\altCover\tools\net45\AltCover.exe /i=C:\work\testProj2\bin\Debug\ /o="C:\temp\__UnitTestWithAltCover" -s=Microsoft.* -s=nunit -s=nlog -s=System.*  /x="ALTCOVER_VSTEST_PROJ2.xml" --opencover
C:\temp\altCover\tools\net45\AltCover.exe /i=C:\work\testProj3\bin\Debug\ /o="C:\temp\__UnitTestWithAltCover" -s=Microsoft.* -s=nunit -s=nlog -s=System.*  /x="ALTCOVER_VSTEST_PROJ3.xml" --opencover

and so on for each test project and then use something like report generator to aggregate results in one file ?

Also how would AltCover know which tool (nunit, vstest or msTest) to run to execute tests and check coverage ? and how to pass additional parameters into the test execution console ? Those details I am after, but could not find unfortunately.

**Comment by SteveGilham** [comment]
Addressing the last paragraph first, this is what the 

* -- ... Anything on the command line after a free-standing "--" is considered a separate command line to be executed after the instrumentation has been done.

does; but I've added an explicit instrument and run case to the [Examples of Use](https://github.com/SteveGilham/altcover/wiki/Examples-of-use#unit-testing-the-net-frameworkmono-build) page, which should hopefully make it clearer.   In this case that would be
```
C:\temp\altCover\tools\net45\AltCover.exe /i=C:\work\testProj1\bin\Debug\ /o="C:\temp__UnitTestWithAltCover" -s=Microsoft.* -s=nunit -s=nlog -s=System.* /x="ALTCOVER_VSTEST_PROJ1.xml" --opencover -- "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" -targetargs:"C:\work\testProj1\bin\Debug\__Instrumented\testProj1.dll 
```
which is exactly the same as breaking into two steps at the `--` like

```
C:\temp\altCover\tools\net45\AltCover.exe /i=C:\work\testProj1\bin\Debug\ /o="C:\temp__UnitTestWithAltCover" -s=Microsoft.* -s=nunit -s=nlog -s=System.* /x="ALTCOVER_VSTEST_PROJ1.xml" --opencover
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" -targetargs:"C:\work\testProj1\bin\Debug\__Instrumented\testProj1.dll 
```

Note
* pointing the test driver at the defaulted location for the instrumented assembly
* in either case you only get a subset of the OpenCover format (just the visit counts, nothing derived from them)

With multiple unit test assemblies, then you'd need to repeat this n times, once per assembly.  

For gluing the reports together, then ReportGenerator will give the overview, and combine cases where an assembly is used in more than one test set for you (if each test covers a different set of assemblies, then you could just manipulate the `<Module>` elements together).

---

The big difference : multiple test runs rather than one.  This is down to the difference in how the programs work -- OpenCover (like NCover) catches each assembly as it's loaded into the executing and instruments it on the fly; AltCover (like minicover and coverlet) have to be told in advance what to instrument and directory level granularity -- "what's in the output folder of that unit test project?" -- is a suitable way to make that guess.

What can be done -- and part of the delay in responding has been doing some pre-design for this --  is to extend AltCover so that it can take a list of folders to instrument (and corresponding outputs), so that one unit test run can invoke many separate instrumented assemblies.

**Comment by alexey-aurea** [comment]
Thank you for the info and enhancement!

**Comment by SteveGilham** [comment]
Multiple input and output directories in a single instrumentation run now supported in new release v6.0.698
