### ISSUE TITLE
Confusing switch case coverage

### ISSUE THREAD

**Issue by cbroxton** [SteveGilham/altcover#72]
Hi,

I've got an issue with some confusing coverage statistics being generated for switch cases. My tests have covered all branches including the default branch however AltCover is still considering there to be a missing branch until I test with null as the value. Here's a screenshot of what the coverage looks like...

![screencapture](https://user-images.githubusercontent.com/497113/64789045-93d5f380-d56b-11e9-89f4-2e7d938c3865.png)

I've also created a simple reproduction of the issue in the following repository...

[AltCoverSwitchCaseTest](https://github.com/cbroxton/AltCoverSwitchCaseTest)

Coverage was generated with the following command...

`dotnet test /p:AltCover=true /p:AltCoverSingle=true /p:AltCoverCobertura="Cobertura.xml" /p:AltCoverAssemblyExcludeFilter="xunit|.Test"`

Is this a bug? Or if not could you please help clear up why there is a missing branch? As far as I can tell in the case that the value is null it should use the default branch which is already covered?

**Comment by SteveGilham** [comment]
The branch processing logic here is ultimately derived from OpenCover's algorithms; and the implicit design philosophy of that tool (as stated in several branch-coverage related issues) is to expose all the compiler generated tangle, and leave it to the end-user to decide which branches are actually sane, and which are compiler generated (and which may not even be coverable e.g. for F# inlines or `match` expressions on an algebraic type).

Currently, AltCover amends that behaviour, hiding simple conditional branches that terminate within the same sequence-point (compiler generated housekeeping often does this), and combining branches from IL `switch` instructions that go to the same location; but otherwise treats each branching instruction individually.  Having already taken a "trust the compiler" approach for these cases (so tests can be focussed more on the program language level logic rather than the compiler's implementation details), it would be worthwhile to take a look at doing some more processing of branches that considers a sequence point as a whole to handle the language level `switch` or `match` constructs.

**Comment by cbroxton** [comment]
Thanks for the detailed response, have to admit though a lot of it went over my head. I've ended up changing the code to be an if, else if instead. The issue was that in our real code the switch case is in a for loop which before the switch case will continue the loop if the value is null so the branch is impossible to reach. Not sure if this is a bug or just an unavoidable thing but I've updated my repo to show the issue.

**Comment by SteveGilham** [comment]
In release v6.2.714, the --visibleBranches option clears the compiler generated clutter from reports to produce what you thought you'd get from a switch statement.

![Untitled1](https://user-images.githubusercontent.com/7460854/65161064-d3e71b80-da2e-11e9-9f44-8a003ff3055a.png)

from command line
```
dotnet test /p:AltCover=true /p:AltCoverSingle=true /p:AltCoverCobertura="Cobertura.xml" /p:AltCoverLocalSource=true /p:AltCoverAssemblyExcludeFilter="?AltCover" /p:AltCoverVisibleBranches=true
```

**Comment by cbroxton** [comment]
That's great thanks, appreciate how quickly you're resolving these issues. I've added the flag to the test step of our pipeline. Feel free to close this.
