### ISSUE TITLE
Just out of curiosity, how altcover works?

### ISSUE THREAD

**Issue by kfrajtak** [SteveGilham/altcover#76]
HI Steve,

great work!

Whenever I run across an interesting project I am immediately curious how it works? Would you be so kind and point me to the part when the magic is happening?

Thanks,
Karel

**Comment by SteveGilham** [comment]
The bit that does the important work is [here](https://github.com/SteveGilham/altcover/blob/f06c296c383020f5c5fd8ecc01dafff4eccc9b38/AltCover/Instrument.fs#L377-L385) -- a function call is inserted into existing method body so that when the method executes past it, that fact can be recorded.  Everything else builds outwards from that.

The [CodeProject article](https://www.codeproject.com/Articles/41722/Building-NET-Coverage-Tool) describing the original concept and implementation gives a bit more background as to what is going on.  AltCover built on that concept, adapting it to handle more complex bits of .net (the original doesn't even handle nested classes), and broader requirements like distinguishing branches, tracking which test method caused a visit, and so on.
