### ISSUE TITLE
Add inclusive filters

### ISSUE THREAD

**Issue by OnurGumus** [SteveGilham/altcover#82]
Altcover has a great deal of exclusion filters. But in some cases we want to exclude a big chunk but include a small portion of it. What I propose to have inclusive versions of below filters:
```
  -f, --fileFilter=VALUE     Optional, multiple: source file name to exclude
                               from instrumentation
  -p, --pathFilter=VALUE     Optional, multiple: source file path to exclude
                               from instrumentation
  -s, --assemblyFilter=VALUE Optional, multiple: assembly name to exclude from
                               instrumentation
  -e, --assemblyExcludeFilter=VALUE
                             Optional, multiple: assembly which links other
                               instrumented assemblies but for which internal
                               details may be excluded
  -t, --typeFilter=VALUE     Optional, multiple: type name to exclude from
                               instrumentation
  -m, --methodFilter=VALUE   Optional, multiple: method name to exclude from
                               instrumentation
  -a, --attributeFilter=VALUE
                             Optional, multiple: attribute name to exclude from
                               instrumentation
```

such that, if the item in covered by an inclusive filter, include it in the instrumentation irrespective of the exclusion filter.

**Comment by SteveGilham** [comment]
Since release 6.2.714, this facility has been available, via a small extension to the regex syntax.

As noted [in the FAQ](https://github.com/SteveGilham/altcover/wiki/FAQ), using a leading `?` -- an otherwise invalid notation -- means exclude all that doesn't match this pattern, i.e. include all that does.

**Comment by OnurGumus** [comment]
Oh that's a feature I didn't know. However, in my case I have doubt that it will help. I think I should be more specific. In my case I happen to use attributes for excluding code. So
```
[<ExcludeCodeCoverage>]
module SomeModule =
    module Helpers
        let someHelper ... = ...
    let someFunctionTobeExcluded ... = ...
```

So in above case SomeModule is already excluded since I use an attribute filter. Now what I want is to include only Helpers. If I just use the question mark to exclude everything from Helpers, then that exclusion would spill everywhere.  Ideally I want to use an IncludeCodeCoverage attribute along with ExcludeCodeCoverage and IncludeCodeCoverage  should over take even if parent is excluded.

**Comment by SteveGilham** [comment]
This case is somewhat more complicated than just exclude-the-inverse -- all exclusions are extended to items textually contained in the affected item, so that if you exclude a type or function, all the types or functions respectively within -- including and especially those compiler generated entities representing lambdas and such, things that you don't directly name or attribute -- will be excluded too.  

So, talkign specifics, with code like
```
[<ExcludeCodeCoverage>]
module SomeModule =
    [<IncludeCodeCoverage>]
    module Helpers
        let someHelper ... = ...
    let someFunctionTobeExcluded ... = ...
```

a typename-based approach like `-t ?Helpers` fails  because `SomeModule` doesn't pass and that exclusion affect the nested module, and with the module falls its functions; just as  `-a ?IncludeCodeCoverage` does.  

It's actually slightly worse than this in the latter case, because if the individual functions within the modules are themselves without attributes, they at the method level, will be excluded by (lack of) attribute, even were the class to pass any `-a` expression including it on account of having a user supplied attribute (ignoring any compiler scattered attributes they might have in common here).

---

So, that's where we are.  

Where we would like to be where we have a mechanism that breaks the current simple enclosing-entity-wins rule in a similarly uncomplicated manner.

I shall have to give this some thought.

**Comment by SteveGilham** [comment]
In the next release. a new (optional, multiple) filter argument `--toplevel` -- class level attributes will be checked against the list of regexes (with leading `?` still meaning match anything but), and if it's a match, the type will ignore the status of any enclosing/declaring type.

For the example above `-a Exclude --toplevel Include` would include the `SomeModule.Helpers` type (and, by default, all types it contains) but exclude function `SomeHelpers.someFunctionTobeExcluded`.  The logic could extend to nested functions, but those cannot be attributed, so there's no point trying.

**Comment by OnurGumus** [comment]
I scratched my head a bit to get it but if I understand correctly if `--toplevel` matches something, that will be checked against the exclusion filter irrespective of its parent.

**Comment by SteveGilham** [comment]
Yes, that's the effect.

**Comment by OnurGumus** [comment]
For the toplevel, can you only specify attribute filters?

**Comment by SteveGilham** [comment]
As currently implemented, yes.

That seemed the simplest way of indicating the exceptions; though names could be added too, making it `--toplevelattributes`, `--topleveltypes`, even `--toplevelmethods` if that would be of use.

**Comment by SteveGilham** [comment]
Published in release v7.0.770 (.771 for the global tool)

**Comment by SteveGilham** [comment]
Assuming that no news is good news.

**Comment by OnurGumus** [comment]
Oh yeah thanks. The newer version of api is better. Though haven't found the chance to test it yet.
