### ISSUE TITLE
No recorder dll in nominated directory

### ISSUE THREAD

**Issue by Nihlus** [SteveGilham/altcover#9]
When using the latest release (v3.0.404), no recorder dll is produced in the selected instrumentation directory. This prevents any coverage from being generated or collected.

The following is a log from instrumentation to collection, including test execution. Disregard any error messages in the test run; these are intentional.

https://hastebin.com/buzayixida.sql

This issues was not present in the previously used version in the project, that is, 2.0.324. The issue presents itself in both `--inplace` and non-inplace runs.

**Comment by SteveGilham** [comment]
The interesting bit of the log is that it's reporting an error from the instrumentation stage (The program should also exit with a non-zero return code)

```
jarl@jax ~/Programming/AdvanceDLSupport $ dotnet altcover/altcover.3.0.404/tools/netcoreapp2.0/AltCover.dll --inputDirectory AdvancedDLSupport.AOT.Tests/bin/Debug/net461 --xmlReport coverage-adl-aot-net461.xml --opencover --assemblyExcludeFilter=.+\.Tests --assemblyExcludeFilter=AltCover.+ --assemblyExcludeFilter=Mono\.DllMap.+ --inplace --save
Creating folder /home/jarl/Programming/AdvanceDLSupport/__Saved
Saving files to /home/jarl/Programming/AdvanceDLSupport/__Saved
Instrumenting files in /home/jarl/Programming/AdvanceDLSupport/AdvancedDLSupport.AOT.Tests/bin/Debug/net461
Value does not fall within the expected range.
```

That last line would be an exception message (which is now being reported in the newer build); though not one that is terribly helpful as it stands.

Since the recorder dll is the last thing written, it's not surprising if it's not there.

I suspect the way forwards is going to include pushing out a release with more error logging than just the exception message, and seeing what it reveals.  A minimum of replacing 
```
    | :? ArgumentException as a -> error <- a.Message :: error
```
with
```
    | :? ArgumentException as a -> error <- a.ToString() :: error
```
in CommandLine.fs at least.

**Comment by Nihlus** [comment]
I'd be happy to test any changes you want. altcover has been a lifesaver up until this point, and this issue (which has replaced a previous, unresolved issue I had) is one of the few things blocking a feature in one of my libraries.

That other issue shows up in the Byakko series as a nondescript failure to run when attempting to instrument or run one of my test projects targeting `net461`. I can provide information on that issue as well, if you'd like.

**Comment by SteveGilham** [comment]
The nondescript failure is going to be a result of the oversight, where I'd packaged up failure information, then forgot to display any of it.  

[Build 409](https://ci.appveyor.com/project/SteveGilham/altcover/build/artifacts) should make the failure more blatant, and log all the exception details to file.  If you could run it for your failure cases and add the results to this thread, that would be super.  If they look to be different root causes, then I'll handle them as separate issues.

**Comment by Nihlus** [comment]
Here's the log. In this particular case, the failures are at the same point, only the altcover versions differ.

[AltCover-2018-04-12--14-10-38.log](https://github.com/SteveGilham/altcover/files/1903016/AltCover-2018-04-12--14-10-38.log)

**Comment by SteveGilham** [comment]
I see the problem.  I sort the instrumentable wheat from the chaff by seeing if Mono.Cecil will load a file as an assembly or not, thus avoiding issues with name base filtering such as executables not necessarily  ending with `.exe` on *nix, or native libraries being part of the mix.  Formerly it used to give success or BadImageFormatException in all the cases I threw at it; this is a case where it gives ArgumentException when reading one of the files.

It's possible that this is a behavioural change in the Cecil 0.10 final release, since that came out in the period between the 2.0.324 and 3.0.400 releases.  That'll be easy to fix, then.

**Comment by SteveGilham** [comment]
[Build 410](https://ci.appveyor.com/project/SteveGilham/altcover/build/artifacts)  handles this particular exception, and also gives feedback of which files have been selected for instrumentation.

I hope to make a proper release this week-end after wrapping up a unit of work for another feature.

**Comment by Nihlus** [comment]
410 also fails, but this time for a different reason.

https://hastebin.com/hexojogehu.rb

[AltCover-2018-04-12--17-42-12.log](https://github.com/SteveGilham/altcover/files/1903915/AltCover-2018-04-12--17-42-12.log)

**Comment by SteveGilham** [comment]
So, it's not finding a reference to assembly 'AdvancedDLSupport, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null'.  Presuming that this is part of the system under test, is it in the list of assemblies selected for instrumentation (the list of "  => path-to-assembly")?  I ask because I'm wondering if this might be the file that Cecil is failing to read with an `ArgumentException`, and I'm not currently logging the failures.

**Comment by Nihlus** [comment]
The hastebin link seems to have died - the assembly is indeed the main assembly under test, and is included in the output log (hastebin).

**Comment by Nihlus** [comment]
Here's the log that hastebin fumbled away.

[log.txt](https://github.com/SteveGilham/altcover/files/1905063/log.txt)

**Comment by SteveGilham** [comment]
The symbol mismatch failure -- not logged to file -- in the new log looks like the result of running a second `--inplace` without having cleaned & rebuilt after a failure, with an inconsistent mix of half-here, half-there assemblies being worked on.

I had an idea overnight, that these problems are all in the depths of Cecil, and started after I'd moved from the 0.10-beta7 release to the final 0.10; so [build 413](https://ci.appveyor.com/project/SteveGilham/altcover/build/3.0.413-pre) is the same as build 410, only I've backed out the Cecil upgrade.

Let's see what happens when that runs on a clean build, and go from there.

**Comment by Nihlus** [comment]
You're absolutely right, my bad. Here are the new logs.

https://hastebin.com/ebalayohak.rb

[AltCover-2018-04-13--12-04-14.log](https://github.com/SteveGilham/altcover/files/1906860/AltCover-2018-04-13--12-04-14.log)

**Comment by SteveGilham** [comment]
Thanks for that.  I have the glimmerings of a idea; shall have to see if I can get a repro.

Meanwhile, did you get a chance to try build 413 yet?

**Comment by Nihlus** [comment]
Ah, good! Spring should hopefully come around here too :P

**Comment by SteveGilham** [comment]
Actually, it turned out to be absurdly obvious once I could get it under a debugger.  Give [build 419](https://ci.appveyor.com/project/SteveGilham/altcover/build/artifacts) a try.

This gives me an insight into another possible class of failures, which I shall work on before I push out another formal release.

**Comment by Nihlus** [comment]
That did it! Thanks a ton :)

**Comment by SteveGilham** [comment]
[New release pushed](https://www.nuget.org/packages/AltCover/3.0.422) with this fix in.

**Comment by Nihlus** [comment]
Everything resolved; Closing issue.
