### ISSUE TITLE
CRAP score is over 255

### ISSUE THREAD

**Issue by OnurGumus** [SteveGilham/altcover#94]
I am getting below error
```
/home/onur/.nuget/packages/altcover/7.1.782/build/netstandard2.0/AltCover.targets(126,5): error : Maximum CRAP score achieved is 675 above the threshold of 255. [/home/onur/projects/irma.ensemble.analytics/tests/Test/Test.fsproj]
```

**Comment by OnurGumus** [comment]
And the report is as below
```
Visited Classes 138 of 555 (24.86)
Visited Methods 179 of 714 (25.07)
Visited Points 333 of 1272 (26.18)
Visited Branches 106 of 1167 (9.08)
Maximum CRAP score 930

==== Alternative Results (includes all methods including those without corresponding source) ====
Alternative Visited Classes 143 of 579 (24.7)
Alternative Visited Methods 201 of 807 (24.91)
Alternative maximum CRAP score 930
```

**Comment by SteveGilham** [comment]
This looks like the expected result for that value of CRAP score and an explicit `/p:AltCoverThreshold=C255` in the command line -- 675 + 255 = 930

What's the command line you are using?

**Comment by OnurGumus** [comment]
I thought by definition crap scores are capped with 255. So I guess I shouldn't have a crap score like 930.
`/p:AltCoverThreshold=S60C255`

**Comment by SteveGilham** [comment]
As a metric, the score is unbounded, increasing with the cyclomatic complexity of the method --

> Let CC(m) = cyclomatic complexity of a method and U(m) = the fraction of a method not covered by unit tests.
> 
> CRAP(m) = CC(m)^2 * U(m)^3 + CC(m).

The 255 limit for the coverage threshold is the maximum value of an unsigned byte, partly for implementation convenience, because that's what the other precentage-based thresholds use, but also because recommendations on complexity usually suggest limiting cyclomatic complexity to values in the mid-teens, so that also gives a reasonable upper bound for likely CRAP scores in the wild (a function with a CC of 15 and zero coverage has a CRAP score of 240)

**Comment by SteveGilham** [comment]
I'm assuming that this is now resolved.
