### ISSUE TITLE
Generate report per test?

### ISSUE THREAD

**Issue by ffMathy** [SteveGilham/altcover#98]
This is something Coverlet can't do, so I'm curious if this is something AltCover is interested in doing.

See https://github.com/coverlet-coverage/coverlet/issues/973 for an explanation on why I'd like something like this.

**Comment by ffMathy** [comment]
More context (from the above issue):

> I want to build a CLI that internally runs tests for you serially (non-parallel) that have been affected by your GIT changes, based on previous coverage.
> 
> That's why I want to be able to see what tests ran through a specific line of code.
> 
> See the examples given in my other issue here: dotnet/aspnetcore#25194

**Comment by SteveGilham** [comment]
The `--callContext` command line option (or its equivalent for other means of invoking instrumentation), based on the similar and earlier OpenCover feature, should achieve what you are looking for.  In the case linked, the context value would be `[TestMethod]`, as that's the test method decoration there.

Call context reporting adds an entry under each sequence point indicating the calling method for each test that visits.  Yes, it can bloat the size of the report file significantly.

In detail, a sequence point gets to look like
```
                <SequencePoint vc="528" uspid="14" ordinal="0" offset="0" sl="15" sc="31" el="15" ec="67" bec="0" bev="0" fileid="1">
                  <Times />
                  <TrackedMethodRefs>
                    <TrackedMethodRef uid="5" vc="264" />
                    <TrackedMethodRef uid="6" vc="264" />
                  </TrackedMethodRefs>
                </SequencePoint>
```
and the `<Module>` entry for the test assembly contains the details for the methods linke4d by their ids
```
      <TrackedMethods>
        <TrackedMethod uid="1" token="100663313" name="System.Void Tests.Problematic::Using FsUnit()" strategy="[Test]" />
        <TrackedMethod uid="2" token="100663314" name="System.Void Tests.Problematic::Using FsUnit bis()" strategy="[Test]" />
        <TrackedMethod uid="3" token="100663317" name="System.Void Tests.Problematic::add6To3 should be odd()" strategy="[Test]" />
        <TrackedMethod uid="4" token="100663318" name="System.Void Tests.Problematic::add6To3 should be odd bis()" strategy="[Test]" />
        <TrackedMethod uid="5" token="100663319" name="System.Void Tests.Problematic::Thing Rectangle()" strategy="[Test]" />
        <TrackedMethod uid="6" token="100663320" name="System.Void Tests.Problematic::Thing Rectangle bis()" strategy="[Test]" />
      </TrackedMethods>
```

**Comment by ffMathy** [comment]
That sounds great Steve! Is there any documentation on this flag and how to use it?

Can I use it with "dotnet test"?

**Comment by SteveGilham** [comment]
Documentation is in the [wiki](https://github.com/SteveGilham/altcover/wiki) (or linked from it), and yes, the option is available in `dotnet test` integration (as `/p:AltCoverCallContext=“<pipe separated list of names or numbers>”`).

Command-line options usage listed [here](https://stevegilham.github.io/altcover/Usage) -- this is a dump of the command line help-text from `altcover -?`
Matching `dotnet test` command parameters are listed [here](https://stevegilham.github.io/altcover/%60dotnet-test%60-integration) -- a few parameters are implied by process (assembly directories, and raw coverage output), but all the rest of the command line tool options are exposed, along with a few that are specific to the `dotnet test` process itself.

**Comment by ffMathy** [comment]
Hmmm but what if I want to run all tests, but still want to see what tests ran through a specific line of code?

With call context, I have to specify a single test, right?

**Comment by SteveGilham** [comment]
No; you can specify multiple tests, either explicitly by name (the command-line option can be given more than once, or a collection of strings for the other means of invocation), or by a common marker attribute.

In particular, supplying as context the marker attribute for unit test methods for the test framework being used will catch every test, as in the example XML above.   The full file (renamed as` .txt` for embedding) is here -- [AltCoverFSharpTests.xml.txt](https://github.com/SteveGilham/altcover/files/5450738/AltCoverFSharpTests.xml.txt)

That's taken from the output of the `FSharpTests` operational test target in the AltCover build.  That case uses the Fake task to drive the `dotnet test` step, with parameters
```
      ({ Primitive.PrepareOptions.Create() with
           XmlReport = simpleReport
           CallContext = [ "[Test]" ]
           AssemblyFilter = [ "Adapter" ]
           TypeFilter = [ "System\\."; "Microsoft\\." ]
           InPlace = true
           ReportFormat = "OpenCover"
           Save = false })
```
Being an NUnit based example, this indicates "show all the tests" by choosing marker attribute `[Test]` -- and as can be seen in the `<TrackedMethods>` result above, multiple test methods have been indicated, with the `strategy` attribute indicating that these methods were selected because they had that attribute.

If you do wish to select only a specific smaller set of tests, then the select by name option can be used to name the test(s) of interest e.g. `/p:AltCoverCallContext=“ThisShouldHappen|SomeOtherCaseFails"` which would only select the two named tests (the third context option, a number for timer granularity, is not germane for this case -- that mode is intended for integration-type tests, to answer the question "what did this test step cover?" by comparing with the wall clock time over which each step executed).

**Comment by SteveGilham** [comment]
[FAQ entry added](https://github.com/SteveGilham/altcover/wiki/FAQ#how-do-i-tell-which-test-covered-which-line-like-with-opencovers-coverbytest-option) to improve usuability, I hope.

**Comment by ffMathy** [comment]
Thank you so far! Is there a way to do it without knowing on beforehand what attribute I am looking for?

Because that differs between the testing frameworks.

**Comment by SteveGilham** [comment]
To be fully general, that would require reverse-engineering the test framework being used on the fly.  To me, that starts to get beyond the responsibility (in the SRP sense) of a coverage tool, and into the realm of the tool that specifically aims to integrate with unit tests.

The poor man's version would be to add the fully qualified attribute names for each of the major frameworks, and add more as demand arises, in the same way that OpenCover's `coverbytest` option hard codes MSTest, XUnit, and NUnit, and suggests that an issue be raised for more.

Slightly more selectively, scanning the test runner to find out which one is being used and creating and attribute entry just for the (well-known) framework that has been selected.  For an unknown case, which should be comparatively rare even prompting the user for the attribute name, or offering to read it from the project file.

FWIW an attribute-based approach doesn't work for the Expecto framework, which relies on an internal list-of-names instead.  I shall have to ponder that one.

**Comment by ffMathy** [comment]
@SteveGilham I got the `callContext` thing working. However, I'd also like a way to specify where `coverage.xml` goes, and how it is named.

For instance, it would be cool if I could specify the directory of where all `coverage.xml` files are placed, even when using `dotnet test` in the solution directory.

Right now, I can use the `--reportXml` flag, but that's per project.

**Comment by SteveGilham** [comment]
The `/p:AltCoverXmlReport=...` option takes a path, not just a file name.  Supplying an absolute path e.g. `$(SolutionDir)\reports\$(ProjectName).coverage.xml` should do the trick.

**Comment by ffMathy** [comment]
That works if I do it from `csproj` properties, but not from the command-line.

If I do it using the command-line, I literally get a file called `$(ProjectName).coverage.xml`, without substituting the `ProjectName` variable in.

**Comment by SteveGilham** [comment]
I was being optimistic there, I guess, assuming that the issue was just one of everything being done from the one working directory.   The notion of a project, like the notion of a test, is something that has to be injected into the instrumentation operation.  

I shall have to do some experiments to see what can be done about this one.

**Comment by ffMathy** [comment]
Alternatively if I could just specify a report directory path instead of a file path, and if it could just name all reports from a random GUID or something, that'd still work for me.

I just want to read all the reports of all projects.

**Comment by ffMathy** [comment]
Today, to read all the reports of a solution, I have to traverse all directories in the whole repository to look for a report file (because I can't know how the developer's project is set up unless I parse the sln file).

I'd like to avoid that for performance reasons.

**Comment by SteveGilham** [comment]
The magic formula for getting at least some MSBuild property values into the report name is by cunning use of quotes, like
```
dotnet test /p:AltCover=true .\Sample4.fsproj "/p:AltCoverXmlReport=""C:/Users/steve/Documents/GitHub/altcover/Sample4/testreport/""`$(ProjectName)"".xml"""
```
which puts all the reports into a folder given by absolute path, but labels them with the project name.  Using `/` as the separator makes it simple and cross-platform (otherwise put in the escaped `\\` on Windows).

* If you are running in a PowerShell context, then you need to put a back-tick in front of the `$` to escape it in too. 
* It doesn't work for `$(SolutionDir)`, which isn't in the macros for a pre- or post-build event, (or `$(ProjectDir)`, which is, for that matter).  I've not tried any other values, but none of the obvious ones seem at all useful.

FWIW, static method invocations also work, like
```
dotnet test /p:AltCover=true .\Sample4.fsproj "/p:AltCoverXmlReport=""/testreport/""`$([System.Guid]::NewGuid())"".xml""" 
```

**Comment by SteveGilham** [comment]
Alas, for `dotnet test` of a solution with multiple test projects, it turns out that the GUID generation is still only done once.

So in the end, it doesn't look like there's a general purpose way to do this just making use of the existing interface and the nuances of MSBuild -- it will need some code changes and a new release.

**Comment by SteveGilham** [comment]
For the purposes of testing with a private local build --

Commit 3177ea56ca441048bb657443630a339b73ea0ab4 contains an updated `AltCover.targets` file that will update the `AltCoverXmlReport` value if it contains one of the following literals

  * $(ProjectName)  
  * $(SolutionDir)  
  * $([System.Guid]::NewGuid())  

with the actual values of those build parameters (where they haven't already been replaced by MSBuild).  These are the most obviously useful ones, but more can be added as need arises.

**Comment by SteveGilham** [comment]
The file naming enhancement is in the [7.1.795 release](https://www.nuget.org/packages/AltCover/7.1.795). Is there anything else needed to resolve this issue?

**Comment by ffMathy** [comment]
No, this is great - thanks!
